# Site settings
title: 'Welcome to 10's space!'
description: 'Here are something about 10'
author:
  name: "Celine"
  email: "1210001414@student.must.edu.mo"
  url:  "https://1010.github.io/"

 baseurl: /
 
 source: .
 destination:  ./_site
 pernalink: /:title
 painate: 3
 painate_path: /page/:num/

author: Armando Maynez # add your name
author-pic: Myself_Neon_grey.jpg
about-author: Engineer, industry executive, research enthusiast. Avid learner with diverse interests in coding, machine learning, artificial intelligence and reinforcement learning. 17+ years of experience working in multinational corporations.

# Contact links
email: armando.maynez@gmail.com # Add your Email address
phone: # Add your Phone number
website: https://amaynez.github.io # Add your website
linkedin: amaynez # Add your Linkedin handle
github: amaynez # Add your Github handle
twitter: '@MvmThe' # Add your Twitter handle
bandcamp: armandomaynez # Add your Bandcamp username
stackoverflow: stackoverflow # Add your stackoverflow account

# Newsletter
mailchimp: "https://github.us1.list-manage.com/subscribe/post?u=8ece198b3eb260e6838461a60&amp;id=397d90b5f4"

# Tracker
analytics: G-R8SZS2YBZK
fbadmin: ar.maybach

# Paginate
paginate: 6
paginate_path: 'page:num'
words_per_minute: 200


plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
